// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAelgoduczhGZxA5AY2Pi4jBBnTxtoDHA0',
    appId: '1:115832952064:web:595390723835faa0c00fe5',
    messagingSenderId: '115832952064',
    projectId: 'snake-ladder-game-c21e9',
    authDomain: 'snake-ladder-game-c21e9.firebaseapp.com',
    storageBucket: 'snake-ladder-game-c21e9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuUFRzkRAnVM2axscdtTOlV-F1iCIhFQo',
    appId: '1:115832952064:android:13e334a6c4441f6fc00fe5',
    messagingSenderId: '115832952064',
    projectId: 'snake-ladder-game-c21e9',
    storageBucket: 'snake-ladder-game-c21e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3lLzqxwrRTV6Fc0BFSWJ3GJQRiuAvFLc',
    appId: '1:115832952064:ios:954b34954956c7d4c00fe5',
    messagingSenderId: '115832952064',
    projectId: 'snake-ladder-game-c21e9',
    storageBucket: 'snake-ladder-game-c21e9.firebasestorage.app',
    iosBundleId: 'com.example.snakeLadderGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3lLzqxwrRTV6Fc0BFSWJ3GJQRiuAvFLc',
    appId: '1:115832952064:ios:954b34954956c7d4c00fe5',
    messagingSenderId: '115832952064',
    projectId: 'snake-ladder-game-c21e9',
    storageBucket: 'snake-ladder-game-c21e9.firebasestorage.app',
    iosBundleId: 'com.example.snakeLadderGame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAelgoduczhGZxA5AY2Pi4jBBnTxtoDHA0',
    appId: '1:115832952064:web:8e8a688da22c1008c00fe5',
    messagingSenderId: '115832952064',
    projectId: 'snake-ladder-game-c21e9',
    authDomain: 'snake-ladder-game-c21e9.firebaseapp.com',
    storageBucket: 'snake-ladder-game-c21e9.firebasestorage.app',
  );
}
